name: Build and Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 我们在这里直接安装所有需要的包，确保万无一失
          pip install beautifulsoup4 requests PyYAML Jinja2 feedparser # <-- 我在这里新增了 feedparser

      - name: Run script to generate index.html
        run: python main.py

      - name: Commit and push index.html
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          if ! git status | grep -q "nothing to commit"; then
            git commit -m "Update index.html with latest data"
            git push
          else
            echo "No changes to commit."
          fi
