name: Build and Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests PyYAML Jinja2 feedparser pytz

      # --- 调试步骤开始 ---
      - name: 1. List files before running script # 1. 运行前，查看目录下有哪些文件
        run: ls -la

      - name: 2. Run script to generate index.html # 2. 运行我们的Python脚本
        run: python main.py

      - name: 3. List files after running script # 3. 运行后，再次查看目录下有哪些文件
        run: ls -la
      # --- 调试步骤结束 ---

      - name: Commit and push index.html
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          if ! git status | grep -q "nothing to commit"; then
            git commit -m "Update index.html with latest data"
            git push
          else
            echo "No changes to commit."
          fi
